### ISSUE TITLE
Conexão com api simuladas.

### ISSUE THREAD

**Issue by Guilherme-Macena** [luizalabs/tutorial-python-brasil#17]
Estou seguindo o tutorial e ao tentar as solicitar itens da api_simulda, tenho um retorno de um "Erro no Servidor Interno", tentei diversas formas e não o consegui seguir a partir disso... desde ja agradeço qualquer ajuda ou sujestão...

**Comment by cassiobotaro** [comment]
@Guilherme-Macena o seu erro foi algo similar a `httptools.parser.errors.HttpParserInvalidMethodError: Invalid method encountered` ? Se for tente mudar a requisição para `http http://...` ao invés de `http https://...`. Caso seja outro erro, poderia me mandar o erro?

**Comment by Guilherme-Macena** [comment]
@cassiobotaro esse é o erro que recebo ao tentar solicitar um pedido. Não consigo compreender se é algum erro de configuração do meu ambiente. mas no meu console aparece esse erro

INFO:     127.0.0.1:51962 - "GET /orders/efb77dcf-d83c-4935-81ac-7be5f37e6cdc/items HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application

**Comment by cassiobotaro** [comment]
@Guilherme-Macena Você seguiu os comando do README? Ou está subindo o ambiente de outra maneira?

**Comment by Guilherme-Macena** [comment]
@cassiobotaro segui os comando do README, poetry install e depois subindo o main:app na porta 8080.

No console da porta 8080, aparece um erro em paralelo, 403 FORBIDEM, quando tento solicitar o item

**Comment by cassiobotaro** [comment]
Vou fazer uma verificação com calma amanhã. Obrigado por reportar.

**Comment by cassiobotaro** [comment]
@Guilherme-Macena Fiz algumas modificações na api simulada, poderia verificar se agora está funcionando corretamente?

**Comment by Guilherme-Macena** [comment]
@cassiobotaro apliquei as atualizações e não recebi mais o mesmo erro ao tentar solicitar os pedidos. acredito que tenha sido corrigido, obrigado pela atenção!!
